name: Staging deployment

on:
  pull_request:
    types: [labeled]

env:
  DOCKER_IMAGE_NAME: FredrikAugust-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  AZURE_WEBAPP_NAME: FredrikAugust-ttt-app
 
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'stage')
